apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: py-docs-api
  namespace: py-docs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-docs-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
