apiVersion: v1
kind: Service
metadata:
  name: py-docs-api
  namespace: py-docs
spec:
  selector:
    app: py-docs-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
